--AppLog database tables


DROP TABLE IF EXISTS T_APP_INFO;

CREATE TABLE T_APP_INFO
(
   ID                   BIGINT NOT NULL  AUTO_INCREMENT COMMENT '自增ID',
   APP_NAME             VARCHAR(64) COMMENT '应用名称',
   CONTACT_TYPE         CHAR(5) COMMENT '联系类型',
   CONTACT_INFO         VARCHAR(255) COMMENT '联系方式',
   SUBJECT         		VARCHAR(255) COMMENT '通知主题',
   RECORD_CRT_TIME      DATETIME  COMMENT '创建时间',
   PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE T_APP_INFO COMMENT '应用信息配置表';


DROP TABLE IF EXISTS T_MESSAGE;

CREATE TABLE T_MESSAGE
(
   ID                   BIGINT NOT NULL  AUTO_INCREMENT COMMENT '自增ID',
   APP_NAME              VARCHAR(64) COMMENT '应用ID',
   NODE                 VARCHAR(128) COMMENT '节点',
   LEVEL                VARCHAR(5) COMMENT '消息的级别',
   MESSAGE              TEXT COMMENT '消息内容',
   RECORD_CRT_TIME    DATETIME  COMMENT '创建时间',
   PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE T_MESSAGE COMMENT '消息通知表';
